### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by jasnell** [domenic/import-maps#17]
First off great to see explorations on this... some feedback.

Consider the following case... 

```
{
  "path_prefix": "/node_modules",
  "packages": {
    "index.js": { "main": "src/index.js" },
  }
}
```

In an application that also has an `index.js` at it's root. What does `import * from 'index.js'` load? That is, how does this deal with naming collisions?

There's a danger here in recreating the hell that is Java classpaths.

Another approach to this could be to take a more generic http/http2 centric approach and allow an origin to declare client-side aliases for various resources. These would amount to a client side 302 or 303 response.

For instance:

```
HTTP/1.1 200 OK
Link: </node_modules/lodash.js>; rel="alias"; anchor="lodash"
Content-Type: application-js

import * from "lodash"
```

**Comment by justinfagnani** [comment]
Thanks!

I'm unsure why would you define a package named "index.js" and import as "index.js", why not just do:

```js
import * from './src/index.js';
```

Which skips the package name map altogether.

Can you further describe why you wanted to define a file as a package?

**Comment by matthewp** [comment]
`import * from 'index.js'` should always load your index.js "package", because it's a bare module specifiers and bare specifiers are always looked up from the packagemap.

**Comment by ljharb** [comment]
It’d be for the same reasons people put symlinks in their node_modules or use a babel transform or webpack alias for the package root; but since the package map would only apply to bare imports - ie, only things that aren’t prefixed with a dot or protocol or slash, iirc - i don’t think there’d be any collision (as said [here](https://github.com/domenic/package-name-maps/issues/17#issuecomment-373831903))

**Comment by matthewp** [comment]
@justinfagnani This is actually going to be `/node_modules/index.js/src/index.js`.  I think @jasnell is bringing this up as a point because there would possibly be a collision of bare specifiers defaulted to normal URL rules.

Once https://github.com/domenic/package-name-maps/issues/6 is complete hopefully that will clarify what happens in the case that a bare specifier doesn't match anything in the packagemap. My hope is that will error like it does today.

**Comment by justinfagnani** [comment]
> Once #6 is complete hopefully that will clarify what happens in the case that a bare specifier doesn't match anything in the packagemap. My hope is that will error like it does today.

Oh definitely, that will throw.

**Comment by jasnell** [comment]
@matthewp ... yes, that's it exactly. The example was a bit off because I threw it together quickly but I'm glad the point came across.

**Comment by domenic** [comment]
The proposal has changed a lot, so let me close this. In the newest iteration, it's intentionally in-scope to allow remapping of URLs like `./src/index.js`, as well as bare specifiers like `index.js`.
