### ISSUE TITLE
Empty array as an alternative to @std/thrower or @std/blank

### ISSUE THREAD

**Issue by domenic** [domenic/import-maps#66]
I think it works. TODO: check in more detail and update readme if so.

**Comment by WebReflection** [comment]
FWIW, I don't see a use case for an explicit `@std/thrower` but I do see use cases for `@std/blank` that never throws (mocked environment, simulated features test, code coverage).

This is because in the main readme it's state that it is possible to:
```js
delete self.WebSocket;
```

but that never throws anything, it lets us monkey-patch/overwrite the env instead, which is desired in some case.

**Comment by domenic** [comment]
I agree `@std/blank` has some uses. But now, I think those are probably left to the built-in modules proposal. Before it was a dependency of this proposal; now it's decoupled, but still IMO a good idea.
