### ISSUE TITLE
A useful mapping algorithm

### ISSUE THREAD

**Issue by blittle** [domenic/import-maps#78]
Under the section, `Programmable Hook Resolution`, I'd like to give an example of a useful mapping algorithm implemented as an extension to SystemJS. Specifically an algorithm that allows the end user of an application (usually developers or qa) to override the module resolution to point to an enumerated or custom environment. Currently our algorithm implementation utilizes simple `localStorage` flags to override the mapping. This allows developers to (in production) override a module to point to their local computer. 

If the `import-maps` specification doesn't allow a programmable hook resolution option, at the very least it would be awesome if dev-tools provided a way to dynamically change the resolution. Then only the dev experiences the performance hit. With programmable mapping, I think this is the kind of creative functionality that becomes possible in user space, because even if one browser implements special functionality in dev tools, it is unlikely that all will.

**Comment by guybedford** [comment]
@blittle the primary limitation of not having a dynamic resolution hook is that it is not possible to resolve _non-predetermined_ imports with the package map. Since import maps can be created dynamically, as long as you know what imports to expect (eg like a package.json can), then you can set everything up fine. But as soon as a new package is imported that wasn't originally expected, that is where import maps will not be able to provide any functionality, while a fully custom resolver in theory could.

Would dynamically generating an import map in production cover your use case, or do you think you come up against the non-predetermined imports problem here?

**Comment by blittle** [comment]
@guybedford a dynamically generated import map would work. Would the mapping have to be server rendered into the HTML file (or a link to a server rendered mapping)? Or could code change the mapping after the page has already loaded?

**Comment by guybedford** [comment]
See https://github.com/domenic/import-maps#dynamic-import-map-example for an example of dynamically injecting an import map from JavaScript. This can only be done before loading any other modules in a sort of "bootstrap" phase.

**Comment by blittle** [comment]
It would help if I read the _whole_ spec :)
